name: Mark All Systems Healthy

on:
  workflow_dispatch: # manual trigger (via UI or GitHub API)

permissions:
  contents: write
  pull-requests: write

jobs:
  mark-healthy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci

      - name: Run Mark All Healthy script
        run: npm run mark-all-healthy

      - name: Commit and push updated files
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add data/status.json
          git commit -m "Mark all systems healthy [bot]" || echo "No changes to commit"
          git push